language: php

php:
    - 5.6
    - 7
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

addons:
  apt:
    packages:
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev
    - python-pip

before_install:
     - pip install autobahntestsuite

before_script:
    - composer install
    - sh test/ab/run_ab_tests.sh

script:
    - phpunit
