language: php
sudo: required

php:
    - 5.6
    - 7
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_install:
     - sudo apt-get install python-pip -qq
     - sudo apt-get install -qq build-essential libssl-dev libffi-dev python-dev python-pip
     - sudo pip install autobahntestsuite

before_script:
    - composer install
    - sh test/ab/run_ab_tests.sh

script:
    - phpunit
